services:
  clamav1:
    image: clamav/clamav:latest
    # ports:
    #   - "3310:3310"
    restart: unless-stopped
    volumes:
      - ./services/clamav/clamd.conf:/etc/clamav/clamd.conf:ro
      - ./services/clamav/freshclam.conf:/etc/clamav/freshclam.conf:ro
      - clamav-db:/var/lib/clamav
    healthcheck:
      test: ["CMD", "sh", "-c", "clamdscan --fdpass /etc/hosts || exit 1"]
      interval: 30s
      retries: 3
      start_period: 60s
      timeout: 10s

  clamav2:
    image: clamav/clamav:latest
    # ports:
    #   - "3310:3310"
    restart: unless-stopped
    volumes:
      - ./services/clamav/clamd.conf:/etc/clamav/clamd.conf:ro
      - ./services/clamav/freshclam.conf:/etc/clamav/freshclam.conf:ro
      - clamav-db:/var/lib/clamav
    healthcheck:
      test: ["CMD", "sh", "-c", "clamdscan --fdpass /etc/hosts || exit 1"]
      interval: 30s
      retries: 3
      start_period: 60s
      timeout: 10s
      
  envoy-av-lb:
    build: ./services/envoy
    volumes:
      - ./services/envoy/envoy-av-lb/envoy.yaml:/etc/envoy/envoy.yaml
    # entrypoint: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --log-level debug
    # ports:
    #   - "3310:3310"
    #   - "8001:8001"
    depends_on:
      clamav1:
        condition: service_healthy
      clamav2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8001/ready"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  redis:
    image: redis:latest
    # ports:
    #   - "6379:6379"
    volumes:
      - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      retries: 3
      start_period: 60s
      timeout: 10s

  worker1:
    build: ./worker
    volumes:
      - temp_storage:/api/temp_storage
    depends_on:
      envoy-av-lb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      CLAMAV_PORT: 3310
      CLAMAV_HOST: envoy-av-lb
      SOCKET_TIMEOUT: 600
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      TEMP_STORAGE_PATH: /api/temp_storage
      AV_REQUESTS_PER_SECOND: 200
      MAX_CONCURRENT_TASKS: 200
      MAX_RETRIES: 5
      VISIBILITY_TIMEOUT: 300 # Seconds
      STALE_TASK_CHECK_INTERVAL: 60 # Seconds
      MAX_PROCESSING_TIME: 300 # # Seconds

  worker2:
    build: ./worker
    volumes:
      - temp_storage:/api/temp_storage
    depends_on:
      envoy-av-lb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      CLAMAV_PORT: 3310
      CLAMAV_HOST: envoy-av-lb
      SOCKET_TIMEOUT: 600
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      TEMP_STORAGE_PATH: /api/temp_storage
      AV_REQUESTS_PER_SECOND: 200
      MAX_CONCURRENT_TASKS: 200
      MAX_RETRIES: 5
      VISIBILITY_TIMEOUT: 900 # Seconds
      STALE_TASK_CHECK_INTERVAL: 60 # Seconds
      MAX_PROCESSING_TIME: 900 # # Seconds

  fastapi1:
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    # ports:
    #   - "8000:8000"
    volumes:
      - temp_storage:/api/temp_storage
    depends_on:
      redis:
        condition: service_healthy
    environment:
      TEMP_STORAGE_PATH: /api/temp_storage
      MAX_FILE_SIZE: 100  # MB
      UPLOAD_CHUNK_SIZE: 8192 # KB
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      MASTER_KEY: ${MASTER_KEY}
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8000/debug/api/v1/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  fastapi2:
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    # ports:
    #   - "8000:8000"
    volumes:
      - temp_storage:/api/temp_storage
    depends_on:
      redis:
        condition: service_healthy
    environment:
      TEMP_STORAGE_PATH: /api/temp_storage
      MAX_FILE_SIZE: 100  # MB
      UPLOAD_CHUNK_SIZE: 8192 # KB
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      MASTER_KEY: ${MASTER_KEY}
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8000/debug/api/v1/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  fastapi3:
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    # ports:
    #   - "8000:8000"
    volumes:
      - temp_storage:/api/temp_storage
    depends_on:
      redis:
        condition: service_healthy
    environment:
      TEMP_STORAGE_PATH: /api/temp_storage
      MAX_FILE_SIZE: 100  # MB
      UPLOAD_CHUNK_SIZE: 8192 # KB
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      MASTER_KEY: ${MASTER_KEY}
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8000/debug/api/v1/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  envoy-api-lb:
    build: ./services/envoy
    volumes:
      - ./services/envoy/envoy-api-lb/envoy.yaml:/etc/envoy/envoy.yaml
    # entrypoint: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --log-level debug
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      fastapi1:
        condition: service_healthy
      fastapi2:
        condition: service_healthy
      fastapi3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8001/ready"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  nginx:
    build: ./services/nginx
    image: nginx:latest
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/static:/static
    # # Uncomment the following lines if you want to mount your own certificates
    #   - ./services/nginx/ssl/nginx.crt:/etc/nginx/ssl/nginx.crt:ro
    #   - ./services/nginx/ssl/nginx.key:/etc/nginx/ssl/nginx.key:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      envoy-api-lb:
        condition: service_healthy
      
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost/"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

volumes:
  redis-data:
  clamav-db:
  temp_storage: